name: Build Python wheels

on: [push, pull_request]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - windows-2019
        - macOS-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install wheel build tool
        run: pip install cibuildwheel==2.13.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SOME_OPTION: value

      - name: Store wheels as build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
